version: "3.2"

services:
  pocketbase:
    build: .
    image: pocketbase-onboarding
    container_name: pocketbase-onboarding
    env_file: .env
    environment:
      PUBLISHER_URL: ${PUBLISHER_URL:-http://host.docker.internal:8080}
    volumes:
      - "./pb_migrations:/pb/pb_migrations"
      - "./pb_hooks:/pb/pb_hooks"
      - "./pb_public:/pb/pb_public"
      - "pb_data:/pb/pb_data"
    ports:
      - "127.0.0.1:${PB_PORT:-8090}:8090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  pb_data:
